#!/bin/bash
# pre-commit git hook to check the validity of puppet manifests, Hiera data and r10k Puppetfile
#
# Prerequisites:
#   gem install puppet-lint
#   gem install r10k
#

function checkyaml() {
  ruby -e "require 'yaml'; YAML.load_file('$1')"
}

echo "### Puppet parser (*.pp) check ###"
for file in `git diff --name-only --cached | grep -E '\.(pp)'`
do
  if [[ -f $file && $file == *.pp ]]
  then
    puppet.bat parser validate $file

    if [[ $? -ne 0 ]]
      then
        syntax_is_bad=1
      fi
    fi
done
echo ""

echo "### Puppet-lint (*.pp) check ###"
for file in `git diff --name-only --cached | grep -E '\.(pp)'`
do
  if [[ -f $file && $file == *.pp ]]
  then
    puppet-lint \
      --no-80chars-check \
      --with-filename $file \
      --no-documentation-check

    if [[ $? -ne 0 ]]
      then
        syntax_is_bad=1
      fi
    fi
done
echo ""

echo "### Puppet templates (*.erb) check ###"
for file in `git diff --name-only --cached | grep -E '\.(erb)'`
do
  if [[ -f $file && $file == *.erb ]]
  then
    erb -P -x -T '-' $file | ruby -c

    if [[ $? -ne 0 ]]
      then
        syntax_is_bad=1
      fi
    fi
done
echo ""

echo "### Hiera data (*.yaml) check ###"
for file in `git diff --name-only --cached | grep -E '\.(yaml)'`
do
    if [[ -f $file ]]
    then
        checkyaml $file
        if [[ $? -ne 0 ]]
        then
            syntax_is_bad=1
        fi
    fi
done
echo ""

echo "### Puppetfile check ###"
for file in `git diff --name-only --cached | grep 'Puppetfile'`
do
    if [[ -f $file ]]
    then
        r10k puppetfile check
        if [[ $? -ne 0 ]]
        then
            syntax_is_bad=1
        fi
    fi
done
echo ""

if [[ $syntax_is_bad -eq 1 ]]
then
  echo "Correct errors above to be able to commit again"
  exit 1
fi
